### ISSUE TITLE
ArrayList<String> 取出来为空

### ISSUE THREAD

**Issue by MakerYan** [NashLegend/AnyPref#1]
@PrefModel("topic_history")
public class HistoryBean
{
	public ArrayList<String> history = new ArrayList<String>();

	public ArrayList<String> getHistory() {

		return history;
	}

	public void setHistory(ArrayList<String> history) {
		this.history = history;
	}

	public void addData(String item) {
		if (!history.contains(item)) {
			history.add(item);
		}
	}
}

存动作:
存的时候对象里的ArrayList对象add了3个数据;
AnyPref.put(有数据的HistoryBean对象, "名字");

取动作:
HistoryBean historyBean = AnyPref.get(HistoryBean.class, "名字");
historyBean 里面的ArrayList有3个item, 但数据全是null,

**Comment by NashLegend** [comment]
首先要添加@PrefArrayList注解；
其次ArrayList声明必须要有泛型信息如ArrayList<String>，否则取出来不知道是啥类~

**Comment by NashLegend** [comment]
另外ArrayList如果存String的话，取出来应该都是""，因为它没有public的字段，建议使用Set<String>，取出来是有序的LinkedHashSet
